### ISSUE TITLE
DRY CSS

### ISSUE THREAD

**Issue by jordanwillis** [photomed21/prj-rev-bwfs-dasmoto#3]
Your CSS looks pretty good as well.  One thing that I would recommend is to go back through your code once you are finished with it and make sure that you have applied the DRY (don't repeat yourself) principle by removing any duplicated and unnecessary properties/styles.  There are several techniques to do this such as using use of combo selectors, factoring out repeated styles into a single class that you can reuse in your HTML, or simply just removing properties that are unnecessary due to the cascading nature of CSS.

In the CSS for you project, it looks like we can remove the extra `font-family` property in your `.blue` selector since you have already applied this style in your first combo selector.

https://github.com/photomed21/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L24

And then assuming that you modified your HTML structure to include the container around each component, we can simplify `.brushes`, `.frames`, and `.paint` selectors like this.

``` css
.item h2 {
  font-size: 32px;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}

#frames {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```

The result is a simplified set of selectors with no property duplication, which will set us up for success in the future for easy extensibility and maintainability.
